hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_AirMSPI_FT_234_clouds_V1_drop_index1_0_0.5_50_ce_weight_zero0.1_cloud1/${now:%H-%M-%S}
seed: 0
debug: False
resume: True
version: 'V2'
stats_print_interval: 1
validation_iter_interval: 1000000000
checkpoint_iteration_interval: 5
#validation_iter_interval: 2500
#checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-06_AirMSPI_BOMEX_aux_8cams_V2_drop_index1/19-46-15/checkpoints/cp_85000.pth'
checkpoint_resume_path: '/wdata/roironen/Deploy/VIPCT/outputs/2023-04-09_AirMSPI_BOMEX_aux_8cams_V2_drop_index1_0_0.5_50_ce_weight_zero0.1_BEST/15-00-39/checkpoints/cp_45000.pth'
gpu: 1
data:
  dataset_name: '32N123W_experiment_all_clouds' # '32N123W_experiment_234_clouds' #'32N123W_experiment_all_clouds' #'CASS_600CCN_roiprocess_10cameras_20m'
  n_training: 1
  n_val: 40
#  n_cam: 10
  n_cam: 8
  drop_index: 1
  rand_cam: False
  mean: 0.017
  std: 0.0072

optimizer:
  max_epochs: 100000
  lr: 5.0e-05
  wd: 1.0e-05
  batch_size: 1
  iter_steps: [1000000000]
  lr_scheduler_gamma: 0.1
  loss: 'L2_relative_error' #'L2_relative_error' # 'CE'
  ce_weight_zero: True
cross_entropy:
  min: 0
#  max: 300
  max: 50
#  bins: 301
  bins: 101
ct_net:
  n_hidden_neurons_xyz: 64
  n_hidden_neurons_dir: 64
  n_layers_xyz: 4
  n_layers_dir: 4
  append_xyz: [2]
  append_dir: [2]
  n_query: 200
  val_n_query: 200
  stop_encoder_grad: True
  mask_type: 'space_carving'  #'space_carving' 'gt_mask' None
  val_mask_type: 'space_carving' #'space_carving'  #'space_carving' 'gt_mask' None
  query_point_method: 'all' #'topk' gt_sc_random
  query_point_val_method: 'all'
  decoder_batchify: True
  use_neighbours: False # penalize model also for voxel neighbours
  pred_type: 'differentiable_max' #'differentiable_max'
  conf_type: 'prob' #conf_interval prob std rel_prob



backbone:
  name: 'resnet50_fpn' #'resnet34' fasterrcnn_resnet50_fpn
  pretrained: False
  num_layers: 4
  index_interp: 'bilinear'
  index_padding: 'zeros' #'zeros', 'border', or 'reflection'
  upsample_interp: 'bilinear'
  feature_scale: 1.0
  use_first_pool: 'batch'
  sampling_support: 6
  sampling_output_size: 18
  out_channels: 64
  n_sampling_nets: 8
  feature_flatten: False
  modify_first_layer: True

decoder:
  name: 'FixCTv4_CE' #'CE' #FixCTv4_CE
  type: 'mlp' #mlp transformer
  masked: False
  num_masked: 20
  average_cams: False
  feature_flatten: True

shdom:
  n_jobs: 35
  use_forward_grid: True
  add_rayleigh: True

#transformer:
#  hidden_dim: 256
#  dropout: 0.1
#  nheads: 1
#  dim_feedforward: 1024
#  num_encoder_layers: 6
#  num_decoder_layers: 6
#  normalize_before: True
